name = "El wiwi"
author = "utime"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d86bf087646d5b6e958d61d93b0dc9615772ecdcfb2b85b58c258a3b2dedf5a2"

[versions]
minecraft = "1.19.2"
quilt = "0.20.2"
