name = "El wiwi"
author = "utime"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56bf3afc0f2ddeab75acb3eb9b125792f8944f0ce35cd937215f7bf74eec0b91"

[versions]
minecraft = "1.19.2"
quilt = "0.20.2"
