# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				bee = true
				axolotl = true
				arrow = true
				cow = true
				pig = true
				skeleton = true
				llama = true
				bat = true
				experience_bottle = true
				rabbit = true
				silverfish = true
				armor_stand = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				turtle = true
				salmon = true
				wandering_trader = true
				wither_skeleton = true
				item_frame = true
				horse = true
				phantom = true
				ender_dragon = true
				leash_knot = true
				llama_spit = true
				glow_squid = true
				glow_item_frame = false
				squid = true
				snowball = true
				creeper = true
				lightning_bolt = true
				enderman = true
				dragon_fireball = true
				chicken = true
				trader_llama = true
				donkey = true
				chest_minecart = true
				tropical_fish = true
				fox = true
				slime = true
				pillager = true
				iron_golem = true
				zombified_piglin = true
				area_effect_cloud = true
				endermite = true
				cat = true
				zombie = true
				ender_pearl = true
				sheep = true
				fireball = true
				player = true
				potion = true
				eye_of_ender = true
				wither_skull = true
				villager = true
				wolf = true
				elder_guardian = true
				boat = true
				polar_bear = true
				painting = true
				cave_spider = true
				witch = true
				cod = true
				spider = true
				wither = true

			[light_sources.settings.entities.botania]
				pixie = true
				mana_burst = true
				magic_missile = true
				doppleganger = true
				flame_ring = true
				babylon_weapon = true
				magic_landmine = true

			[light_sources.settings.entities.betternether]
				chair = true

			[light_sources.settings.entities.hwg]
				flare = true
				grenade = true
				flame_firing = true
				blazerod = true
				technodemon_greater_1 = true
				shell = true
				merc = true
				rockets = true
				mbullets = true
				spy = true
				fireball = true
				bullets = true

			[light_sources.settings.entities.create]
				stationary_contraption = true
				gantry_contraption = true
				super_glue = true

			[light_sources.settings.entities.mca]
				grim_reaper = true
				male_zombie_villager = true
				female_zombie_villager = true
				female_villager = true
				male_villager = true

			[light_sources.settings.entities.portalcubed]
				portal_1_storage_cube = true
				portal_1_companion_cube = true
				adventure_core = true
				chair = true
				old_ap_cube = true
				hoopy = true
				experimental_portal = true
				radio = true
				storage_cube = true

			[light_sources.settings.entities.automobility]
				automobile = true

			[light_sources.settings.entities.deeperdarker]
				stalker = true
				sculk_leech = true

			[light_sources.settings.entities.adorn]
				seat = true

			[light_sources.settings.entities.railways]
				conductor = true

