# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				item = true
				bee = true
				turtle = true
				wolf = true
				arrow = true
				wandering_trader = true
				salmon = true
				cow = true
				polar_bear = true
				item_frame = true
				horse = true
				skeleton = true
				cat = true
				zombie = true
				cave_spider = true
				glow_squid = true
				glow_item_frame = false
				squid = true
				spider = true
				creeper = true
				player = true

			[light_sources.settings.entities.create]
				stationary_contraption = true
				super_glue = true

			[light_sources.settings.entities.mca]
				female_villager = true
				male_villager = true

			[light_sources.settings.entities.automobility]
				automobile = true

			[light_sources.settings.entities.railways]
				conductor = true

